package Final;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public abstract class ReportGenerator {

    public final String generateReport(Admin admin) {

        String report = "";

        report += writeTitle();
        report += writeSummary();
        report += writeContent();
        report += writeFooter(admin);

        return report;
    }

    protected String writeTitle() {
        return "========================================\n";
    }

    protected String writeSummary() {
        return "SUMMARY: System Statistical Report\n";
    }

    protected abstract String writeContent();

    protected String writeFooter(Admin admin) {
        return "\n========================================\n" +
               "Generated By: " + admin.getName() + "\n" +
               "Date: " + LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")) + "\n" +
               "========================================\n";
    }
}